export const  extractApi = 'http://localhost:5000/download'
export const submitApi = 'http://localhost:5000/sweets/create-renarration'
export const getAllRenarrations = 'http://localhost:5000/sweets/renarrations'
export const uploadFileApi = 'http://localhost:5000/upload'
export const serverApi = 'http://localhost:5000'