export const  extractApi = 'http://localhost:3000/download'
export const submitApi = 'http://localhost:3000/sweets/create-renarration'
export const getAllRenarrations = 'http://localhost:3000/sweets/renarrations'
export const uploadFileApi = 'http://localhost:3000/upload'
export const serverApi = 'http://localhost:3000'