export const  extractApi = 'https://renarration-api.onrender.com/download'
export const submitApi = 'https://renarration-api.onrender.com/sweets/create-renarration'
export const getAllRenarrations = 'https://renarration-api.onrender.com/sweets/renarrations'
export const uploadFileApi = 'https://renarration-api.onrender.com/upload'
export const serverApi = 'https://renarration-api.onrender.com'